### ISSUE TITLE
Detect http/s in pasted url

### ISSUE THREAD

**Issue by FD-** [MuShare/Httper-Android#1]
When a url is pasted into the app from the clipboard, it would be great if it could automatically detect if the url starts with http:// or https://, select the corresponding value in the scheme box and strip it from the pasted url.

As it stands now, whenever a url (including the scheme) is pasted, the scheme has to be manually removed from the url after pasting and the scheme has to be manually adjusted in the scheme box.

**Comment by dklaputa** [comment]
Thank you! It is a nice suggestion. We will add this feature in our next release.
